### ISSUE TITLE
如何融合RTK数据

### ISSUE THREAD

**Issue by insistyxj** [gaoxiang12/faster-lio#13]
高博，如果想在目前的fster_lio中加入rtk信息，主要是想用RTK 来修正里程计的位姿。这个RTK信息的使用可以放在IEKF中一起迭代么，还是做一个后融合就可以了呢。

**Comment by gaoxiang12** [comment]
可以，如果RTK和激光同步，那么就在观测方程中添加几行对R和T的观测即可，推导一下相应的雅可比阵。RTK单独观测也可以。
不过原版FastLIO2基于MTK来表达状态变量，改起来可能麻烦一些。

**Comment by insistyxj** [comment]
好的 谢谢高博。我之后改入看一下效果。

**Comment by OliverShaoPT** [comment]
> 好的 谢谢高博。我之后改入看一下效果。

我使用gtsam后端融合RTK数据，在SLAM前端不退化的情况下，效果还可以。老哥在观测方程中融合效果如何呢？
