### ISSUE TITLE
 fatal error: execution: No such file or directory

### ISSUE THREAD

**Issue by srinivasrama** [gaoxiang12/faster-lio#15]

**Comment by xiaotaw** [comment]
c++17 is required.

**Comment by srinivasrama** [comment]
@xiaotaw Thanks

**Comment by ameysutavani** [comment]
Hi @xiaotaw and @srinivasrama I am facing the same issue; how did you resolve it?. My environment is Ubuntu 18.04, ros-melodic gcc7.5.0 and trying to build with catkin_make. I am pretty sure my environment is able to compile c++17 projects.

**Comment by xiaotaw** [comment]
It needs a higher version of gcc and g++. [Compile: Compile in Ubuntu 18.04 or earlier]( https://github.com/gaoxiang12/faster-lio#compile)
