### ISSUE TITLE
Question about visualize NCLT dataset

### ISSUE THREAD

**Issue by Taeyoung96** [gaoxiang12/faster-lio#17]
@gaoxiang12  
Hi, Thanks for your great work!  
I have some questions about visualizing NCLT dataset with faster-lio.  
Actually, my question is not really related to faster-lio algorithm but visualizing the NCLT dataset's ground pose.  

I want to visualize the result plot like faster-lio paper,  

![Screenshot from 2022-05-06 16-50-09](https://user-images.githubusercontent.com/41863759/167090203-dcc38e6d-287e-4507-9abe-a59c5ccfe9ae.png)

However, when I download the `groundtruth.csv` on the [original NCLT homepage](http://robots.engin.umich.edu/nclt/index.html#documentation),  
The data format is quite different from `traj.txt`(Estimated trajectory).  

How could I align `groundtruth.csv` and `traj.txt`?   
Any resources or tips to help align the timestamp and align with the GT and LiDAR coordinate system?   

Thanks,

**Comment by xiaotaw** [comment]
hello, we convert `groundtruth.csv` into 'tum' format (`traj.txt` is already in 'tum' format), then use (evo)[https://github.com/MichaelGrupp/evo] to plot.

**Comment by Taeyoung96** [comment]
@xiaotaw   
Thanks for your reply.  
Is there any recommended codes or links that convert `groundtruth.csv` to 'tum' format?  

I'm newbie so I have difficulty because `groundtruth.csv` is first format that I haven't seen yet. :(

**Comment by xiaotaw** [comment]
There is no off-the-shelf code kept in my computer. It's very easy to write several python or c++ lines of code for this. Just read the trajectory from csv file and re-write them into a file in tum format. For tum format, here is a intro https://github.com/MichaelGrupp/evo/wiki/Formats#tum---tum-rgb-d-dataset-trajectory-format

**Comment by Taeyoung96** [comment]
@xiaotaw   
Thanks, I'll try it by referring your link and NCLT original paper. 👍
