### ISSUE TITLE
Question about creating the NCLT sample bag file.

### ISSUE THREAD

**Issue by Taeyoung96** [gaoxiang12/faster-lio#18]
@xiaotaw  
Hi, I have some questions about [NCLT sample dataset](https://github.com/gaoxiang12/faster-lio#prepare-the-datasets).  

On the original [NCLT homepage](http://robots.engin.umich.edu/nclt/index.html#top), there are no official bag files but, `tar.gz` files.  
So I use [nclt2ros](https://github.com/bierschi/nclt2ros) repository to make the bag file.  

For example, when I make my own bag file for `2013-01-10`seuquence, I was able to create a ros topic like below.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167798880-a03a7730-79ce-4ba4-85d0-391adf8458f7.png" width = "600" ></p>  

I execute the sequence(2013-01-10) and the [config file](https://github.com/gaoxiang12/faster-lio/blob/main/config/velodyne.yaml) (just change the topic name).  

And I got a weird result. :sob:   

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167776606-8064bae8-f042-470f-ba5b-cd120ddf0ed0.png" width = "500" ></p>   

The output of the terminal is below.
<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167776961-17d9fc3a-9522-48f7-9479-7e593958c00e.png" width = "700" ></p>   

---  

And I exectue the same sequence with same [config file](https://github.com/gaoxiang12/faster-lio/blob/main/config/velodyne.yaml) with your sample Dataset, it works fine!  

On the [sample dataset](https://github.com/gaoxiang12/faster-lio#prepare-the-datasets), ros topic is like below.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167800452-11f099d9-4dfd-41a8-8954-759d7d30c805.png" width = "500" ></p>   
 
Result is like below.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167778273-dcbe018b-32a6-424a-9108-bff315f3f863.png" width = "500" ></p>   

The output of the terminal is below.  
<p align="center"><img src="https://user-images.githubusercontent.com/41863759/167778352-f2eb3531-5325-45ca-994c-9540aeac22f1.png" width = "800" ></p>   

I think the difference between two terminals are   
```
Failed to find match for field 'time'
Failed to find match for field 'ring'
```   

What causes this result? Any help would be greatly appreciated.  

Thanks,

**Comment by xiaotaw** [comment]
The sample dataset comes from FAST-LIO2, https://github.com/hku-mars/FAST_LIO#4-rosbag-example. Maybe, I am not sure, it differs from the one generated via nclt2ros.

**Comment by Taeyoung96** [comment]
@xiaotaw   
Thanks for your reply. I will refer to the link to solve the problem.
