### ISSUE TITLE
 faster-lio有用到C++17不同于低版本（如C++11/14）的新特性吗？

### ISSUE THREAD

**Issue by liang0724s** [gaoxiang12/faster-lio#2]
readme有提到“Since FasterLIO use cpp 17 as its standard (which requires a higher version of g++), you should upgrade the compiler and use the earlier tbb library provided in the thirdparty of this repo.”

faster-lio能否使用低版本C++，如C++11/14？

**Comment by gaoxiang12** [comment]
我们主要用了cpp17中的std::execution来实现并发的for循环，这样程序本体可以简单很多。
这部分可以用omp或者原生tbb来写，那样就可以用c11标准，只是实现层面要复杂一些。
