### ISSUE TITLE
iVox modularizing

### ISSUE THREAD

**Issue by engcang** [gaoxiang12/faster-lio#26]
Hi. Thank you for sharing your great work. The SLAM works super well and super fast in real-world [video](https://youtu.be/kr9Z2e8I7YQ). 

I am also separately using `iVox` for mapping purpose, since this seems the core for the fast mapping of your algorithm.
I just wonder if you are planning to create a separate, new repository for soley `iVox` itself. 
If so, I guess many researchers can utilize your great library with Forks and as Submodules and improve it by many PRs.

I am also trying to add some functions such as `GetAllPoints` for visualizing, `RadiusSearch`, and `BoxSearch`.
and I guess may others are trying to develop more.

Thanks.

**Comment by gaoxiang12** [comment]
Hi @engcang ,

Glad to know that you like our work. iVox is currently placed in a separate directory and is header-only: [ivox3d](https://github.com/gaoxiang12/faster-lio/tree/main/include/ivox3d), so integration should be easy for other people. I will consider saving a standalone repository for it.

And I also plan to remove the CPP 17 requirements (basically the multi-thread for_each) and the MTK library (it's very hard to read). However by doing that the results may be different from that in our paper.
