### ISSUE TITLE
Increasing scan detail 

### ISSUE THREAD

**Issue by rlabs-oss** [gaoxiang12/faster-lio#27]
Hi, 
    Which parameter(s) are responsible for the overall scan detail? - currently its very sparse compared with a static scan. 
I tested a walk with the map in memory and the accuracy was amazing, but I'd like to increase the density/details. 
The Avia lidar is in non-repeating mode and I'm not sure how to start it in repeating via the config if this would help ? 

Thank you.

**Comment by gaoxiang12** [comment]
Hi @rlabs-oss 

The point cloud used for registration is downsampled to a preset resolution which normally equals the voxel size.
The finally saved map will use the raw resolution from your sensor, which is much denser than the point cloud in the local map. If you are running in the online mode, the raw resolution map will also be published in Rviz, like the video [here](https://www.youtube.com/watch?v=kr9Z2e8I7YQ) .

**Comment by rlabs-oss** [comment]
parameter dense_publish_en: seems to be the main one. It will save the raw sensor scan if true. - if false its down-sampled which is great for memory conservation. true will show the spiral scan pattern of the avia at the expense of using more memory, and an aesthetically less pleasing scan.
