### ISSUE TITLE
最邻近严格性的问题

### ISSUE THREAD

**Issue by Torchmm** [gaoxiang12/faster-lio#32]
你好高博：
        我想问问NearBy26是不是就是严格的最邻近了。另外论文中对于LIO在平面残差的情况下不需要严格的最邻近，是不是可以理解成就算不是严格最邻近的5个点，可能构成的平面也一样，那是否有可能因为不严格的最邻近导致构成平面不一致。经过测试，我发现Fasterlio和fastlio在某些退化环境下有一些精度上的差异，所以我想是不是最邻近的问题，但是我使用NearBy26出来的结果和nearby18差别不是很大，故而很困惑。

**Comment by gaoxiang12** [comment]
26也不是严格最近邻啊，搜的范围都是有限的，如果k近邻里有一个在很远的地方依然是收不到的。26相比18只是搜的格子多一些。
精度差异有时候比较玄学，如果点云没有明显退化迹象，轨迹精度相差10cm左右是正常现象。对于faster，你可以尝试把栅格调大一点试试。

**Comment by Torchmm** [comment]
我明白了，谢谢高博！
