### ISSUE TITLE
为什么回调函数需要添加线程锁，而同步函数不需要添加线程锁？

### ISSUE THREAD

**Issue by Dy-314** [gaoxiang12/faster-lio#70]
高博您好，想向您请教一个比较基础的问题。
我在看代码过程中发现，`LaserMapping::****CallBack()`函数中都有添加线程锁，但是在`LaserMapping::SyncPackages()`函数中并没有添加线程锁，但是这两者都有对`lidar_buffer_`进行读写操作，想请问您为什么在这种情况下不会发生冲突呢？

**Comment by gaoxiang12** [comment]
offline模式是串行调用的，这个其实不用任何锁。
online模式外边调的是spinOnce，那个和spin()一样是单线程的，所以实际也不用加锁。。
如果是多线程的spin，那syncPackages内部应该是要有锁的

**Comment by Dy-314** [comment]
好的，谢谢高博
